create table apartments (
    id bigint primary key,
    title text,
    position int,
    price_usd float,
    price_uah float,
    number_rooms int,
    floor_located int,
    number_of_floors_in_the_house int,
    apartment_area int,
    offer_type text,
    wall_type text,
    construction_period text,
    heating text,
    city_id int,
    city_name text,
    latitude float,
    longitude float,
    description text,
    tags text[],
    image_urls text[],
    absolute_url text);
